name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: rustlang/rust:nightly
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run check
        run: cargo check
      - name: Run check
        run: cargo test